### ISSUE TITLE
Serial Breakout RX/TX swapped

### ISSUE THREAD

**Issue by deltaphi** [deltaphi/c6021light#7]
As [reported by user markra in the stummiforum](https://www.stummiforum.de/viewtopic.php?p=2225311&sid=e822d6b1ebf340fec8044f3fbb1adf17#p2225311), on the first version of the PCB, the RX and TX lines for the serial header seem to be swapped.

Lines are not swapped when using a CH340.

**Comment by GBert** [comment]
Fixed in PCB V1.3
